INSERT INTO Products (PRODID, PRODNAME, ARTICLE, COLOR, PRODDATE, COUNTRY, PRODPRICE, CURRENCY) VALUES ('20', 'Носки', ' XX100001, ‘Серый', ' 2020-01-01', 'Украина', '5', 'UAH');
INSERT INTO Products (PRODID, PRODNAME, ARTICLE, COLOR, PRODDATE, COUNTRY, PRODPRICE, CURRENCY) VALUES ('20', 'Носки', ' XX100002, ‘Коричневый', ' 2020-01-01', 'Украина', '5', 'UAH');
INSERT INTO Products (PRODID, PRODNAME, ARTICLE, COLOR, PRODDATE, COUNTRY, PRODPRICE, CURRENCY) VALUES ('20', 'Носки', ' XX100003, ‘Черный', ' 2020-01-01', 'Украина', '5', 'UAH');
INSERT INTO Products (PRODID, PRODNAME, ARTICLE, COLOR, PRODDATE, COUNTRY, PRODPRICE, CURRENCY) VALUES ('20', 'Носки', ' XX100004, ‘Красный', ' 2020-01-01', 'Украина', '5', 'UAH');
INSERT INTO Products (PRODID, PRODNAME, ARTICLE, COLOR, PRODDATE, COUNTRY, PRODPRICE, CURRENCY) VALUES ('20', 'Носки', ' XX100005, ‘Красный', ' 2020-01-01', 'Украина', '5', 'UAH');
